Name = 'IDWR field data'
FirstLineIsHeader = true

[LocationColumn]
ColumnHeader = 'Please type in the site name:'

[[CommentColumns]]
ColumnHeader = 'Comments:'

[[CommentColumns]]
Prefix = 'Maintenance Issues: '
ColumnHeader = 'Maintenance Issues:'

[[PartyColumns]]
ColumnHeader = 'Examiner:'

[[TimestampColumns]]
Format = 'M/d/yyyy h:m:s tt'
Type = 'DateAndSurvey123Offset'
ColumnHeader = 'Visit Date:'

[[TimestampColumns]]
Format = 'H:m'
Type = 'TimeOnly'
ColumnHeader = 'Visit Time:'

[[ReadingColumns]]
ParameterId = 'HG'
UnitId = 'ft'
CommentPrefix = '#1 Staff Gage'
ColumnHeader = 'Staff Gage Reading 1 (ft):'

[[ReadingColumns]]
ParameterId = 'HG'
unitid = 'ft'
CommentPrefix = '#2 Staff Gage'
ColumnHeader = 'Staff Gage Reading 2 (ft):'

[[ReadingColumns]]
ParameterId = 'QR'
UnitId = 'ft^3/s'
CommentPrefix = '#1 Flow Meter'
ColumnHeader = 'Flow Meter Reading 1 (cfs):'

[[ReadingColumns]]
ParameterId = 'QR'
UnitId = 'ft^3/s'
CommentPrefix = '#2 Flow Meter'
ColumnHeader = 'Flow Meter Reading 2 (cfs):'

[[ReadingColumns]]
ParameterId = 'QR'
UnitId = 'ft^3/s'
CommentPrefix = 'Measured discharge'
ColumnHeader = 'Discharge Measured in CFS'
