LocaleName = 'fr-FR' # Use the French locale
Location = '@Le Site'
Time = '@La Date'
Separator =';' # Since the comma is used a decimal point

[Reading]
Value = '@La Température'
ParameterId = 'TA'
UnitId = 'degC'
