# This is our hint that it's an MF Pro file.
PrefaceMustContain = 'Model: MF pro'

Location = '/^Profile Name:\s*(?<value>.+)\s*$/'

# The next two settings tell the plugin that everything comes from the preface.
MaximumPrefaceLines = 0
NoDataRowsExpected = true

# The multi-line option must be enabled via the 'm' after the trailing backslash, to match across a newline.
# This is because the line FOLLOWING the 'Operator Name: xxxx' line is the only line with a timestamp we can parse.
# Yeah, it's weird. But yay, it works! Regex FTW!!
Time = '/^Operator Name: [^\t\n\r]+[\t\r\n]+(?<value>[^\t\r\n]+)/m'

[PanelDischargeSummary]
MeterType = 'Adv'
MeterCalibrationModel = 'MF Pro'
MeterCalibrationManufacturer = 'OTT'

# Parse the other measurement values using regular expressions
TotalDischarge  = '/^Total Discharge: (?<value>\S+) \S+\s*$/'
DischargeUnitId = '/^Total Discharge: \S+ (?<value>\S+)\s*$/{Units}'
DistanceUnitId  = '/^Stream Width: \S+ (?<value>\S+)\s*$/{Units}'
WidthValue = '/^Stream Width: (?<value>\S+) \S+\s*$/'
AreaValue   = '/^Total Area: (?<value>\S+) \S+\s*$/'
AreaUnitId  = '/^Total Area: \S+ (?<value>\S+)\s*$/{Units}'
MeanIndexVelocity = '/^Mean Velocity: (?<value>\S+) \S+\s*$/'
VelocityUnitId = '/^Mean Velocity: \S+ (?<value>\S+)\s*$/{Units}'
NumberOfVerticals = '/^# of Stations: (?<value>.+)\s*$/'
MeterCalibrationSerialNumber = '/^s\/n: (?<value>.+)\s*$/'
MeterCalibrationFirmwareVersion = '/^Boot: (?<value>.+)\s*$/'
MeterCalibrationSoftwareVersion = '/^Application: (?<value>.+)\s*$/'

[Aliases.Units]
'lps' = 'l/s'

[Aliases.StartPoint]
'Right edge water' = 'RightEdgeOfWater'
'Left edge water' = 'LeftEdgeOfWater'

[Aliases.DischargeMethod]
'Mid-section' = 'MidSection'
'Mean-section' = 'MeanSection'